name: Lint commits

on: [push, pull_request]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint:
    name: Lint commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Save Code Linting Report JSON
          run: npm run lint:report
          continue-on-error: true
      - name: Annotate Code Linting Results
        # see https://github.com/ataylorme/eslint-annotate-action
        uses: ataylorme/eslint-annotate-action@v2
        with:
          report-json: "eslint_report.json"